#!/usr/bin/env python

import rospy
import rospkg
from math import pow, atan2, sqrt
from tf.transformations import *

import smach
import smach_ros
from smach_ros import SimpleActionState
from smach_ros import ServiceState
from std_msgs.msg import Int8
from std_msgs.msg import String
import threading

# Manipulator 
from open_manipulator_msgs.msg import JointPosition
from open_manipulator_msgs.msg import KinematicsPose
from open_manipulator_msgs.msg import OpenManipulatorState
from open_manipulator_msgs.srv import SetJointPosition
from open_manipulator_msgs.srv import SetKinematicsPose
from open_manipulator_msgs.srv import GetJointPosition
from open_manipulator_msgs.srv import GetKinematicsPose

import time
from darknet_ros_msgs.msg import BoundingBoxes
from darknet_ros_msgs.msg import BoundingBox
from sensor_msgs.msg import JointState

import tty, sys
import os

from geometry_msgs.msg import PoseArray, Pose
from tf.transformations import euler_from_quaternion, quaternion_from_euler
from darknet_ros_msgs.msg import BoundingBoxes
from darknet_ros_msgs.msg import BoundingBox
import tf
from enum import Enum

class cheersActionByYoloJsk(smach.State):
    def __init__(self):
        smach.State.__init__(self, outcomes=['succeeded', 'aborted','option1','option2','option3'],
                                    input_keys=['input_planning_group'])


        self.detected = {}
        self.detection_names = rospy.get_param('/darknet_ros/yolo_model/detection_classes/names')
	self.object_pose_sub = rospy.Subscriber('/cluster_decomposer/centroid_pose_array', PoseArray, self.collectJsk)
        self.listener = tf.TransformListener()


	self.object_pose_sub = rospy.Subscriber('/darknet_ros/bounding_boxes', BoundingBoxes, self.collect)


        self.cupboundingBox = BoundingBox()
        self.set_joint_position = rospy.ServiceProxy('/open_manipulator/goal_joint_space_path', SetJointPosition)
        self.set_kinematics_position = rospy.ServiceProxy('/open_manipulator/goal_task_space_path_position_only', SetKinematicsPose)
	self.set_joint_position_from_present = rospy.ServiceProxy('/open_manipulator/goal_joint_space_path_from_present', SetJointPosition)
        self.open_manipulator_joint_states_sub_ = rospy.Subscriber('/open_manipulator/joint_states', JointState, self.jointStatesCallback)
        self.open_manipulator_kinematics_pose_sub_ = rospy.Subscriber('/open_manipulator/gripper/kinematics_pose', KinematicsPose, self.kinematicsPoseCallback)
        self.open_manipulator_states_ = rospy.Subscriber('/open_manipulator/states', OpenManipulatorState, self.StatesCallback)
        self.last_detect_time = rospy.get_rostime()
        self.jointStates = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
	self.kinematicsStates = [0.0, 0.0, 0.0]
        rospy.logwarn(' cheersActionByYoloJsk ')
        self.trans = [0.0 , 0.0 , 0.0]
        self.command_Key_sub = rospy.Subscriber('command_Key', String, self.commandKeyCallback)
        self.mode = 9
        self.last_detect_time = rospy.get_rostime()
        self.last_yolodetect_time = rospy.get_rostime()
        self.open_manipulator_moving_state = "STOPPED"

        self.StepCupTracking = Enum('StepCupTracking',
                                       'waiting_signal \
                                        go_backward_location \
                                        wait_detecting_tf_of_cup \
                                        go_base_location \
                                        go_tf_location_of_cup \
                                        wait_finish_movement \
                                        close_cup \
                                        kick_cup \
                                        exit')

        self.pre_step = self.StepCupTracking.exit.value
        #self.step = self.StepCupTracking.waiting_signal.value
        self.step = self.StepCupTracking.go_backward_location.value

    def StatesCallback(self, msg):	
        self.open_manipulator_moving_state = msg.open_manipulator_moving_state

    def commandKeyCallback(self, msg):
        #rospy.logwarn('1commandKeyCallback %d', msg.data) 
        if msg.data == "0" :
            self.mode = 0
        elif msg.data == "1" :   
            self.mode = 1
        elif msg.data == "2" :
            self.mode = 2
        elif msg.data == "3" :
            self.mode = 3
        elif msg.data == "4" :
            self.mode = 4
        elif msg.data == "5" :
            self.mode = 5
        elif msg.data == "8" :
            self.mode = 8
        else :
            pass

    def kinematicsPoseCallback(self, msg):
        self.kinematicsStates[0] = msg.pose.position.x
        self.kinematicsStates[1] = msg.pose.position.y
        self.kinematicsStates[2] = msg.pose.position.z
        #rospy.logwarn(' kinematicsPoseCallback %.2f , %.2f, %.2f  ', self.kinematicsStates[0], self.kinematicsStates[1], self.kinematicsStates[2] )

    def jointStatesCallback(self, msg):
	#rospy.logwarn('jointStatesCallback %d ', len(msg.position) )
        for i, pose in enumerate(msg.position):
            self.jointStates[i] = pose
            #print 'boundingBoxe {} {} '.format(i, pose)

    def collectJsk(self, msg):
        for i, pose in enumerate(msg.poses):
            if pose != Pose():                
                try:
                    #(trans1,rot1) = self.listener.lookupTransform('map', 'yolo_output'+str(i), rospy.Time(0))
		    #(trans,rot) = self.listener.lookupTransform('camera_link', 'yolo_output'+str(i), rospy.Time(0))
		    (trans,rot) = self.listener.lookupTransform('link1', 'yolo_output'+str(i), rospy.Time(0))
		    pos = pose.position
		    val = [round(pos.x,2), round(pos.y,2), round(pos.z,2), round(trans[0],2), round(trans[1],2) , round(trans[2],2)]
                    key = self.detection_names[i]  		
                    #self.update_key(key, val)
		    #print 'Found a {} at {} num{} TF {} '.format(key, val, i, trans)
                    self.trans[0] = round(trans[0],2)
                    self.trans[1] = round(trans[1],2)
                    self.trans[2] = round(trans[2],2)
                    self.last_detect_time = rospy.get_rostime()
                except (tf.LookupException, tf.ConnectivityException, tf.ExtrapolationException):
                    rospy.logwarn('there is no tf ')


    def collect(self, msg):
        for i, boundingBox in enumerate(msg.bounding_boxes):
            #print 'boundingBoxe {} {} '.format(i, boundingBox)
	    if boundingBox.Class == "cup" or boundingBox.Class == "wine glass" :
                self.cupboundingBox = boundingBox
		self.last_yolodetect_time = rospy.get_rostime()
		#self.last_detect_time = rospy.get_rostime()
		#rospy.logwarn('cup withd : %d , z : %.2f', self.cupboundingBox.xmax - self.cupboundingBox.xmin, elf.cupboundingBox.xmin.Z )

    def stop_movement(self, userdata):
        joint_position = JointPosition()
        joint_position.joint_name = ['joint1','joint2','joint3','joint4']  
        joint_position.position =  [0, 0, 0, 0]
        planning_group = userdata.input_planning_group
        try:    
            path_time = 1                    
            resp1 = self.set_joint_position_from_present(planning_group,joint_position, path_time)
            rospy.sleep(path_time)
        except rospy.ServiceException, e:
            print "Service call failed: %s"%e

    def execute(self, userdata):
        print "Send Position by Joint Control "
        joint_position = JointPosition()
        joint_position.joint_name = ['joint1','joint2','joint3','joint4']  
        joint_position.position =  [0, 0, 0, 0]
        planning_group = userdata.input_planning_group
        end_effector_name = "gripper";     
        kinematics_pose = KinematicsPose()
        cup_tf = [0, 0, 0]   
        self.mode = 9

	while 1:

            if rospy.is_shutdown() or self.mode == 8 or self.mode == 1 or self.mode == 2 or self.mode == 3:
                break

            elif self.mode == 4 :
                self.stop_movement(userdata)
                self.step = self.StepCupTracking.waiting_signal.value
                pass

            if self.step == self.StepCupTracking.waiting_signal.value:
                #rospy.logwarn("waiting_signal")
                if self.mode == 5 :
                    self.pre_step = self.StepCupTracking.waiting_signal.value
                    self.step = self.StepCupTracking.go_backward_location.value
	        else :
                    pass

            if self.step == self.StepCupTracking.go_backward_location.value:
                rospy.logwarn("go_backward_location")
                #rospy.sleep(3)
                joint_position.position =  [0, -1.551, -0.234, 1.98]
                path_time = 2.5
                try:
                    resp1 = self.set_joint_position(planning_group,joint_position, path_time)
	            #print 'resp1 {}'.format(resp1.is_planned) 
	            rospy.sleep(path_time) 
                except rospy.ServiceException, e:
                    print "Service call failed: %s"%e

                self.pre_step = self.StepCupTracking.go_backward_location.value
                self.step = self.StepCupTracking.wait_detecting_tf_of_cup.value

            elif self.step == self.StepCupTracking.wait_detecting_tf_of_cup.value:
                #rospy.logwarn("wait_detecting_tf_of_cup")
                rospy.sleep(3)
	        object_detect_duration = rospy.get_rostime().to_sec() - self.last_detect_time.to_sec()
	        #rospy.logwarn("duration %.2f",object_detect_duration )
                tmp_x = self.trans[0]
                tmp_y = self.trans[1]
                tmp_z = self.trans[2] 
                distance = math.sqrt(tmp_x**2 + tmp_y**2 + tmp_z**2)
                width = self.cupboundingBox.xmax - self.cupboundingBox.xmin
 	        #rospy.sleep(0.5)
	        if object_detect_duration > 1 or tmp_x > 0.5 or distance >0.7 or tmp_z < 0.05 or tmp_x < 0.07 or self.cupboundingBox.Z < 0.01 :
	            rospy.logwarn(" no object.. ")
                    pass
                else : 
                    radian = math.atan(tmp_y/tmp_x)
                    degree = math.degrees(radian)
                    dist = 0.1	
                    distX = math.cos(radian)*dist
                    distY = math.sin(radian)*dist
                    rospy.logwarn("tmp_xyz %.2f,%.2f,%.2f _ radian %.2f(%.2f) distXY %.3f , %.3f",tmp_x,tmp_y,tmp_z,radian, degree, distX, distY )
                    cup_tf = [tmp_x - distX , tmp_y - distY, tmp_z + 0.05]
                    self.pre_step = self.StepCupTracking.wait_detecting_tf_of_cup.value
                    self.step = self.StepCupTracking.go_base_location.value

            elif self.step == self.StepCupTracking.go_base_location.value:
                rospy.logwarn("go_base_location")

                joint_position.position =  [0, -1.292, 0.242, 1.342]
                path_time = 1.5
                try:
                    resp1 = self.set_joint_position(planning_group,joint_position, path_time)
	            #print 'resp1 {}'.format(resp1.is_planned) 
	            rospy.sleep(path_time) 
                except rospy.ServiceException, e:
                    print "Service call failed: %s"%e

                self.pre_step = self.StepCupTracking.go_base_location.value
                self.step = self.StepCupTracking.go_tf_location_of_cup.value

            elif self.step == self.StepCupTracking.go_tf_location_of_cup.value:
                rospy.logwarn("go_tf_location_of_cup")

                kinematics_pose.pose.position.x =  cup_tf[0]
                kinematics_pose.pose.position.y =  cup_tf[1]
                kinematics_pose.pose.position.z =  cup_tf[2]
                distance = math.sqrt(cup_tf[0]**2 + cup_tf[1]**2 + cup_tf[2]**2)
                operating_time = distance * 7 / 0.6
                if operating_time < 3 :
                    operating_time = 3 
                try: 
                    resp1 = self.set_kinematics_position(planning_group, end_effector_name, kinematics_pose, operating_time)
	            print 'kinemetics resp1 {} time '.format(resp1.is_planned, operating_time) 
                    rospy.sleep(0.1)
                except rospy.ServiceException, e:
                    print "Service call failed: %s"%e

                self.pre_step = self.StepCupTracking.go_tf_location_of_cup.value
                self.step = self.StepCupTracking.wait_finish_movement.value

            elif self.step == self.StepCupTracking.wait_finish_movement.value:
                
                object_yolodetect_duration = rospy.get_rostime().to_sec() - self.last_yolodetect_time.to_sec()
                width = self.cupboundingBox.xmax - self.cupboundingBox.xmin
                centX = self.cupboundingBox.X
                centy = self.cupboundingBox.Y
                rospy.logwarn("wait_finish_movement %s , width, %d ", self.open_manipulator_moving_state, width)
                rospy.sleep(1)
                if object_yolodetect_duration < 0.5 and width>300 :
                    self.stop_movement(userdata)
                    self.pre_step = self.StepCupTracking.wait_finish_movement.value
                    self.step = self.StepCupTracking.close_cup.value
                    rospy.logwarn("if .............  1 w %.2f", width)                    
                elif self.open_manipulator_moving_state == OpenManipulatorState.STOPPED :
                    self.pre_step = self.StepCupTracking.wait_finish_movement.value
                    self.step = self.StepCupTracking.close_cup.value
                    rospy.logwarn("if ................................................2 w %.2f", width)
                else :
                    rospy.logwarn("if .............  3 w %.2f", width)

            elif self.step == self.StepCupTracking.close_cup.value:    
	        object_yolodetect_duration = rospy.get_rostime().to_sec() - self.last_yolodetect_time.to_sec()            
                width = self.cupboundingBox.xmax - self.cupboundingBox.xmin
                centX = self.cupboundingBox.X
                centY = self.cupboundingBox.Y
                cameraCenX =390 # 320
                cameraCenY =450 # 240
                range_x = 100
                range_y = 100
                minX = cameraCenX - range_x
                maxX = cameraCenX + range_x
                minY = cameraCenY - range_y
                maxY = cameraCenY + range_y
                move_x = 0
                move_y = 0

	        if object_yolodetect_duration > 1 :
                    self.stop_movement(userdata)                    
                    self.pre_step = self.StepCupTracking.close_cup.value
                    self.step = self.StepCupTracking.exit.value
                    continue

                if minX < centX and centX < maxX and minY < centY and centY < maxY :
                    self.stop_movement(userdata)
                    self.pre_step = self.StepCupTracking.close_cup.value
                    self.step = self.StepCupTracking.kick_cup.value   
                    rospy.logwarn("1close_cup centXY %.2f  ( %.2f, %.2f ), %.2f ( %.2f, %.2f )_%.2f,%.2f_w %.2f",\
                                    centX, minX, maxX ,centY ,minY, maxY,move_x, move_y, width)

                else :
                    if centX < minX : 
                        #turn left
                        move_x = 0.03 
                    elif centX > maxX : 
                        #turn right
                        move_x = -0.03 
                    if centY < minY : 
                        #turn up
                        move_y = -0.03 
                    elif centY > maxY : 
                        #turn down
                        move_y = 0.03   
                    rospy.logwarn("2close_cup centXY %.2f  ( %.2f, %.2f ), %.2f ( %.2f, %.2f )_%.2f,%.2f_w %.2f",\
                                    centX, minX, maxX ,centY ,minY, maxY,move_x, move_y, width)             
                    try:
                        joint_position.position =  [move_x, 0, 0, move_y]
                        resp1 = self.set_joint_position_from_present(planning_group,joint_position, 0.5)
                        rospy.sleep(0.2)  
	                print 'resp2 {}'.format(resp1.is_planned) 
                    except rospy.ServiceException, e:
                        print "Service call failed: %s"%e

            elif self.step == self.StepCupTracking.kick_cup.value:
                try:
                    joint_position.position =  [0, 0.2, -0.3, 0]
                    resp1 = self.set_joint_position_from_present(planning_group,joint_position, 1)
                    rospy.sleep(1)  
	            print 'resp2 {}'.format(resp1.is_planned) 
                    rospy.sleep(1) 
                    joint_position.position =  [0, -0.2, 0.3, 0]
                    resp1 = self.set_joint_position_from_present(planning_group,joint_position, 2)
                    rospy.sleep(2)  
	            print 'resp2 {}'.format(resp1.is_planned) 
                except rospy.ServiceException, e:
                    print "Service call failed: %s"%e    
                self.pre_step = self.StepCupTracking.kick_cup.value
                self.step = self.StepCupTracking.exit.value 

            elif self.step == self.StepCupTracking.exit.value:
                rospy.logwarn("exit")
                #rospy.sleep(3)
                self.pre_step = self.StepCupTracking.exit.value
                self.step = self.StepCupTracking.go_backward_location.value

        if self.mode == 1 :
	    return 'option1' #SERVE_FOOD
        elif self.mode == 2 : 
	    return 'option2' #RELEASE_CUP
        elif self.mode == 3 : 
	    return 'option3' #TALKING
        else :
	    return 'succeeded'

class waitCommand(smach.State):
    def __init__(self):
        smach.State.__init__(self, outcomes=['succeeded','aborted','option0','option1','option2','option3','option4','option5'])
        self.command_Key_sub = rospy.Subscriber('command_Key', String, self.commandKeyCallback)
        self.mode = 9

    def commandKeyCallback(self, msg):
        #rospy.logwarn('1commandKeyCallback %d', msg.data) 
        if msg.data == "0" :
            self.mode = 0
        elif msg.data == "1" :
            self.mode = 1
        elif msg.data == "2" :
            self.mode = 2
        elif msg.data == "3" :
            self.mode = 3
        elif msg.data == "5" :
            self.mode = 5
        elif msg.data == "6" :
            self.mode = 6
        else :
            pass

    def execute(self, userdata):
        self.mode = 9
        #print '0. Pour Mode\n1. Cheer Mode\n2. Release Cup\n3. Finish \n' 
        
        while 1 :
            if rospy.is_shutdown() or self.mode == 0 or self.mode == 1 or self.mode == 2 or self.mode == 3 or self.mode == 5 or self.mode == 6:
                break

        if self.mode == 0 :
            rospy.logwarn('Start Pour Mode')
            return 'option0' 
        elif self.mode == 1 :
            rospy.logwarn('Start SERVE_FOOD')        
            return 'option1' 
        elif self.mode == 2 :
            rospy.logwarn('Start RELEASE_CUP')        
            return 'option2' 
        elif self.mode == 3 :
            rospy.logwarn('Start TALKING')        
            return 'option3' 
        elif self.mode == 5 :
            rospy.logwarn('Start Cheers')        
            return 'option5' 
        elif self.mode == 6 :
            rospy.logwarn('PICK CUP')        
            return 'option4' 
        else :
            return 'succeeded' 
    
class fileAction(smach.State):
    
    def __init__(self):
        smach.State.__init__(self, outcomes=['succeeded', 'aborted'],
                                    input_keys=['input_planning_group',
                                                'input_motionfile_file'])

        self.set_joint_position = rospy.ServiceProxy('/open_manipulator/goal_joint_space_path', SetJointPosition)
        self.set_gripper_position = rospy.ServiceProxy('/open_manipulator/goal_tool_control', SetJointPosition)
        self.count = 0

    def execute(self, userdata):
        inputfile = userdata.input_motionfile_file
        self.count = 0
	while 1:
            if rospy.is_shutdown() :
                break
            if self.count > ( len(inputfile) - 1 ):
                break

	    if self.count == 0 :
                position_path_time = 2 
                gripper_path_time = 1 
                operating_time = 2
            else :
                position_path_time = 0.5
                gripper_path_time = 0.5
                operating_time = 0.2

            try: 
	        joint_position = JointPosition()
	        planning_group = userdata.input_planning_group
	        joint_position.joint_name = ['joint1','joint2','joint3','joint4']
                joint_position.position =  [inputfile[self.count][0], inputfile[self.count][1], \
                                            inputfile[self.count][2], inputfile[self.count][3]]
                path_time = position_path_time
                resp1 = self.set_joint_position(planning_group,joint_position, position_path_time)
	        #print 'resp1 {}'.format(resp1.is_planned) 
	        #rospy.sleep(position_path_time) 
            except rospy.ServiceException, e:
                print "Service call failed: %s"%e
            
            try: 
	        gripper_position = JointPosition()
	        planning_group = userdata.input_planning_group
	        gripper_position.joint_name = ['gripper']
                gripper_position.position =  [inputfile[self.count][4]]
                path_time = gripper_path_time
                resp1 = self.set_gripper_position(planning_group,gripper_position, gripper_path_time)
	        #print 'resp1 {}'.format(resp1.is_planned) 
	        #rospy.sleep(0.2) 
            except rospy.ServiceException, e:
                print "Service call failed: %s"%e

            self.count = self.count + 5
            rospy.sleep(operating_time)

	return 'succeeded'

def main():
    rospy.init_node('pick_and_place_state_machine2')
    namespace = rospy.get_param("~robot_name")
    planning_group = rospy.get_param("~planning_group")
    detection_type = rospy.get_param("~detection_type")
    pick_center = smach.StateMachine(outcomes=['succeeded','aborted','preempted','option0','option1','option2','option3','option4','option5'])
   
    rospack = rospkg.RosPack()
    rospack.list() 
    package_path = rospack.get_path('open_manipulator_potman')
    rospy.logwarn("detection_type %s",detection_type )

    with open(package_path+'/cfg/output_pour.txt') as data:
        inputfile_pour = [[float(i) for i in line.split(",")] for line in data.readlines()]
        #print(numbers[0])

    with open(package_path+'/cfg/output_serve.txt') as data:
        inputfile_serve = [[float(i) for i in line.split(",")] for line in data.readlines()]
        #print(numbers[0])

    with pick_center:
        pick_center.userdata.planning_group = planning_group

        def joint_position_request_cb(userdata, request):
            request.joint_position.joint_name = ['joint1','joint2','joint3','joint4']
            request.joint_position.position = userdata.input_position
            request.path_time = userdata.input_time
            return request

        def joint_position_response_cb(userdata, response):
            if response.is_planned == False:
                rospy.sleep(userdata.input_time)
                return 'aborted'
            else:
                rospy.sleep(userdata.input_time)
                return 'succeeded'

        def gripper_request_cb(userdata, request):
            request.joint_position.joint_name = ['gripper']
            request.joint_position.position = userdata.input_gripper
            request.path_time = userdata.input_time
            return request

        def gripper_response_cb(userdata, response):
            if response.is_planned == False:
                #return 'aborted'
                rospy.sleep(userdata.input_time)
                return 'succeeded'
            else:
                rospy.sleep(userdata.input_time)
                return 'succeeded'
        
        pick_center.userdata.potman_init_position = [0.0, -1.05, 0.35, 0.70]
        pick_center.userdata.potman_init_position_time = 3
        smach.StateMachine.add('POTMAN_INIT_POSITION',
                                ServiceState('/open_manipulator/goal_joint_space_path',
                                             SetJointPosition,
                                             request_cb=joint_position_request_cb,
                                             response_cb=joint_position_response_cb,
                                             input_keys=['input_planning_group',
                                                         'input_time',
                                                         'input_position']),
                                transitions={'succeeded':'WAIT_COMMAND'},
                                #transitions={'succeeded':'CHEERS_SEQUENCE'},
                                remapping={'input_planning_group':'planning_group',
                                            'input_time':'potman_init_position_time',
                                            'input_position':'potman_init_position'})

        smach.StateMachine.add('WAIT_COMMAND', waitCommand(),
                                transitions={'succeeded':'WAIT_COMMAND',
                                             'option0':'POUR_ALCOHOL',
                                             'option1':'SERVE_FOOD',
                                             #'option1':'succeeded',
                                             'option2':'RELEASE_FIRST_POSITION',
                                             #'option3':'TALKING',
                                             'option3':'succeeded',
                                             'option4':'PICK_FIRST_POSITION',
                                             'option5':'CHEERS_SEQUENCE',
                                             'aborted':'aborted'})

        pick_center.userdata.motionfile_pour = inputfile_pour	    
        smach.StateMachine.add('POUR_ALCOHOL', fileAction(),
                                transitions={'succeeded':'PICK_FIRST_POSITION',
                                             'aborted':'succeeded'},
                                remapping={'input_planning_group':'planning_group', 
                                           'input_motionfile_file':'motionfile_pour'})

        pick_center.userdata.motionfile_serve = inputfile_serve	    
        smach.StateMachine.add('SERVE_FOOD', fileAction(),
                                transitions={'succeeded':'WAIT_COMMAND',
                                             'aborted':'succeeded'},
                                remapping={'input_planning_group':'planning_group', 
                                           'input_motionfile_file':'motionfile_serve'})

        ########## PICKING CUP ##################################################
        pick_center.userdata.pick_first_position = [0.0, -0.097, 1.361, -0.905]
        pick_center.userdata.pick_first_position_time = 3
        smach.StateMachine.add('PICK_FIRST_POSITION',
                                ServiceState('/open_manipulator/goal_joint_space_path',
                                             SetJointPosition,
                                             request_cb=joint_position_request_cb,
                                             response_cb=joint_position_response_cb,
                                             input_keys=['input_planning_group',
                                                         'input_time',
                                                         'input_position']),
                                transitions={'succeeded':'PICK_GRIPPER_OPEN'},
                                remapping={'input_planning_group':'planning_group',
                                           'input_time':'pick_first_position_time',
                                            'input_position':'pick_first_position'})

        pick_center.userdata.pick_open_gripper = [0.01]
        pick_center.userdata.pick_open_gripper_time = 0.5
        smach.StateMachine.add('PICK_GRIPPER_OPEN',
                                ServiceState('/open_manipulator/goal_tool_control',
                                             SetJointPosition,
                                             request_cb=gripper_request_cb,
                                             response_cb=gripper_response_cb,
                                             input_keys=['input_planning_group',
                                                         'input_time',
                                                         'input_gripper']),
                                transitions={'succeeded':'PICK_SECOND_POSITION'},
                                remapping={'input_planning_group':'planning_group',
                                           'input_time':'pick_open_gripper_time',
                                           'input_gripper':'pick_open_gripper'})


        pick_center.userdata.pick_second_position = [0.0, 0.431, 0.703, -1.069]
        pick_center.userdata.pick_second_position_time = 2
        smach.StateMachine.add('PICK_SECOND_POSITION',
                                ServiceState('/open_manipulator/goal_joint_space_path',
                                             SetJointPosition,
                                             request_cb=joint_position_request_cb,
                                             response_cb=joint_position_response_cb,
                                             input_keys=['input_planning_group',
                                                         'input_time',
                                                         'input_position']),
                                transitions={'succeeded':'PICK_GRIPPER_CLOSE'},
                                #transitions={'succeeded':'succeeded'},
                                remapping={'input_planning_group':'planning_group',
                                           'input_time':'pick_second_position_time',
                                            'input_position':'pick_second_position'})

        pick_center.userdata.pick_close_gripper = [0.0039]
        pick_center.userdata.pick_close_gripper_time = 2
        smach.StateMachine.add('PICK_GRIPPER_CLOSE',
                                ServiceState('/open_manipulator/goal_tool_control',
                                             SetJointPosition,
                                             request_cb=gripper_request_cb,
                                             response_cb=gripper_response_cb,
                                             input_keys=['input_planning_group',
                                                         'input_time',
                                                         'input_gripper']),
                                transitions={'succeeded':'PICK_THIRD_POSITION'},
                                remapping={'input_planning_group':'planning_group',
                                           'input_time':'pick_close_gripper_time',
                                           'input_gripper':'pick_close_gripper'})

        pick_center.userdata.pick_third_position = [0.0, -1.049, 0.359, 0.716]
        pick_center.userdata.pick_third_position_time = 3
        smach.StateMachine.add('PICK_THIRD_POSITION',
                                ServiceState('/open_manipulator/goal_joint_space_path',
                                             SetJointPosition,
                                             request_cb=joint_position_request_cb,
                                             response_cb=joint_position_response_cb,
                                             input_keys=['input_planning_group',
                                                         'input_time',
                                                         'input_position']),
                                transitions={'succeeded':'CHEERS_SEQUENCE'},
                                #transitions={'succeeded':'succeeded'},
                                remapping={'input_planning_group':'planning_group',
                                           'input_time':'pick_third_position_time',
                                            'input_position':'pick_third_position'})

        ########## TRACKING CUP ##################################################
        smach.StateMachine.add('CHEERS_SEQUENCE', cheersActionByYoloJsk(),
                                transitions={'succeeded':'succeeded',
                                             'option1':'SERVE_FOOD',
                                             #'option1':'succeeded',
                                             'option2':'RELEASE_FIRST_POSITION',
                                             #'option3':'TALKING',
                                             'option3':'succeeded',
                                             'aborted':'succeeded'},
                                remapping={'input_planning_group':'planning_group'})

        ########## RELEASE CUP ##################################################

        pick_center.userdata.release_first_position = [0.0, -0.485, 1.173, -0.472]
        pick_center.userdata.release_first_position_time = 2
        smach.StateMachine.add('RELEASE_FIRST_POSITION',
                                ServiceState('/open_manipulator/goal_joint_space_path',
                                             SetJointPosition,
                                             request_cb=joint_position_request_cb,
                                             response_cb=joint_position_response_cb,
                                             input_keys=['input_planning_group',
                                                         'input_time',
                                                         'input_position']),
                                transitions={'succeeded':'RELEASE_SECOND_POSITION'},
                                #transitions={'succeeded':'succeeded'},
                                remapping={'input_planning_group':'planning_group',
                                           'input_time':'release_first_position_time',
                                            'input_position':'release_first_position'})

        pick_center.userdata.release_second_position = [0.0, 0.431, 0.703, -1.069]
        pick_center.userdata.release_second_position_time = 3
        smach.StateMachine.add('RELEASE_SECOND_POSITION',
                                ServiceState('/open_manipulator/goal_joint_space_path',
                                             SetJointPosition,
                                             request_cb=joint_position_request_cb,
                                             response_cb=joint_position_response_cb,
                                             input_keys=['input_planning_group',
                                                         'input_time',
                                                         'input_position']),
                                transitions={'succeeded':'RELEASE_GRIPPER_OPEN'},
                                #transitions={'succeeded':'succeeded'},
                                remapping={'input_planning_group':'planning_group',
                                           'input_time':'release_second_position_time',
                                            'input_position':'release_second_position'})

        pick_center.userdata.release_open_gripper = [0.01]
        pick_center.userdata.release_open_gripper_time = 2
        smach.StateMachine.add('RELEASE_GRIPPER_OPEN',
                                ServiceState('/open_manipulator/goal_tool_control',
                                             SetJointPosition,
                                             request_cb=gripper_request_cb,
                                             response_cb=gripper_response_cb,
                                             input_keys=['input_planning_group',
                                                         'input_time',
                                                         'input_gripper']),
                                transitions={'succeeded':'POTMAN_INIT_POSITION'},
                                remapping={'input_planning_group':'planning_group',
                                           'input_time':'release_open_gripper_time',
                                           'input_gripper':'release_open_gripper'})

        ########## RELEASE CUP END ##################################################


    sis = smach_ros.IntrospectionServer('server_name', pick_center, '/PICK_CENTER')
    sis.start()

    # Execute SMACH plan
    outcome = pick_center.execute()

    # Wait for ctrl-c to stop the application
    rospy.spin()
    sis.stop()

if __name__ == '__main__':
    main()
